language: node_js
os: linux
sudo: required
dist: trusty
addons:
node_js:
  - '10'
  - '12'
  - '14'
install:
  - yarn bootstrap
script:
  - npm run test ci
after_success:
  - if [[ `node -v` == *"v12"* ]]; then (cat coverage/lcov.info | coveralls); ficache:
cache:
  yarn: true
  directories:
    - node_modules
