language: node_js
os: linux
sudo: required
dist: trusty
addons:
node_js:
  - '8'
  - '10'
  - '12'
install:
  - yarn bootstrap
script:
  - npm run test ci
after_success:
  - cat coverage/lcov.info | coveralls
