language: node_js
os: linux
dist: trusty
addons:
node_js:
  - '10'
  - '12'
install:
  - yarn bootstrap
script:
  - npm run test ci
after_success:
  - if [[ `node -v` == *"v12"* ]]; then (cat coverage/lcov.info | coveralls); fi
